# Generated by Django 4.2.11 on 2024-05-18 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UploadedFile',
            new_name='FileModel',
        ),
    ]
